[package]
name = "tn-math"
version = "0.1.0"
edition = "2021"

[dependencies]

[features]
default = [] # Nessuna feature attiva di default
feature1 = [] # Feature indipendente
feature2 = [] # Un'altra feature
